name: data
on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch: null
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check out repo
        uses: actions/checkout@v4
      - name: curl
        uses: wei/curl@v1
        with:
          args: -O  https://www.basketball-reference.com/leagues/NBA_2025.html
      - name: Postprocess
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable ./postprocess.ts
      - name: Configure Git
        run: |
          git config --global user.name 'casey-github-actions[bot]'
          git config --global user.email 'casey-github-actions[bot]@users.noreply.github.com'
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Automated commit of files generated by Deno"
          git push
