name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.espn.com/nba/standings
          downloaded_filename: NBA_2023.html
          postprocess: ./postprocess.ts
